backend:
  name: github
  repo: basilikst/zadaniya_site
  branch: main

media_folder: "files"
public_folder: "/zadaniya_site/files"

collections:
  - name: "tasks"
    label: "Задания"
    files:
      - label: "Список заданий"
        name: "tasks"
        file: "tasks.json"
        fields:
          - label: "Задания"
            name: "tasks"
            widget: "list"
            fields:
              - label: "Дата"
                name: "date"
                widget: "datetime"
                format: "YYYY-MM-DD"
              - label: "Название задания"
                name: "title"
                widget: "string"
              - label: "Файл"
                name: "file"
                widget: "file"
