backend:
  name: github
  repo: basilikst/zadaniya_site
  branch: main

media_folder: "files"
public_folder: "/files"

collections:
  - name: "tasks"
    label: "Задания"
    folder: "tasks"
    create: true
    slug: "{{date}}-{{slug}}"
    fields:
      - { label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Название задания", name: "title", widget: "string" }
      - { label: "Файл задания", name: "file", widget: "file" }
