backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "tasks"
    label: "Задания"
    folder: "tasks"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Название", name: "title", widget: "string" }
      - { label: "Дата сдачи", name: "due", widget: "datetime" }
      - { label: "Описание", name: "body", widget: "markdown" }
      - { label: "Файл", name: "file", widget: "file", required: false }
