backend:
  name: git-gateway
  branch: main

media_folder: "files"
public_folder: "/files"

collections:
  - name: "tasks"
    label: "Задания"
    file: "tasks.json"
    format: "json"
    fields:
      - label: "Список заданий"
        name: "tasks"
        widget: "list"
        fields:
          - { label: "Дата", name: "date", widget: "string" }
          - { label: "Название", name: "title", widget: "string" }
          - { label: "Файл", name: "file", widget: "file", required: false }
